apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
  labels:
    app: devsecops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
        - name: devsecops-demo
          image: devsecops-demo:local
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo-service
spec:
  selector:
    app: devsecops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
